#!/usr/bin/env python3
"""Owner-decisions register: every finding NOT yet verified-fixed, with its reason.

Scans repo-deep-dive runs, joins findings.json (severity/title) with the follow-up
register (status/owner/target/note), and lists the open/owner-gated items a human must
decide — so close-out owners have a single checklist.

Usage:
  tools/owner_decisions.py --runs-dir runs [--out OWNER_DECISIONS.md] [--json out.json]
"""

import argparse
import datetime
import json
import os
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_findings  # noqa: E402

CLOSED = {"verified-fixed"}
ORDER = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}


def load_json(path, default):
    if os.path.isfile(path):
        try:
            return json.load(open(path, encoding="utf-8-sig"))
        except Exception:
            return default
    return default


def is_run(path):
    return os.path.isfile(os.path.join(path, "findings.json")) or \
        os.path.isfile(os.path.join(path, "audit_manifest.json"))


def repo_label(run, manifest):
    cand = manifest.get("repo") or ""
    if cand:
        base = os.path.basename(str(cand).rstrip("/\\"))
        if base:
            return base
    parent = run.parent.name
    if parent and parent not in ("runs", "audits") and not __import__("re").match(r"^\d{8}-\d{4}-", parent):
        return parent
    return run.name


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--runs-dir", required=True)
    ap.add_argument("--out", default=None)
    ap.add_argument("--json", dest="json_path", default=None)
    args = ap.parse_args()

    run_dirs = []
    for root, dirs, _ in os.walk(args.runs_dir):
        dirs[:] = [d for d in dirs if d != ".git"]
        if is_run(root) and os.path.isfile(os.path.join(root, "follow_up_register.md")):
            run_dirs.append(Path(root))
            dirs[:] = []

    rows = []
    for run in run_dirs:
        manifest = load_json(str(run / "audit_manifest.json"), {})
        findings = {f["id"]: f for f in load_json(str(run / "findings.json"), {}).get("findings", [])}
        reg = lib_findings.register_fields(str(run))
        items = []
        for fid, fields in reg.items():
            st = (fields.get("status") or "open").strip().lower() or "open"
            if st in CLOSED:
                continue
            f = findings.get(fid, {})
            items.append({
                "id": fid,
                "severity": f.get("severity") or fid.split("-")[1],
                "title": f.get("title", ""),
                "status": st,
                "note": fields.get("note", ""),
            })
        items.sort(key=lambda i: (ORDER.get(i["severity"], 9), i["id"]))
        if items:
            rows.append({"repo": repo_label(run, manifest), "run": run.name, "items": items})

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = ["# Owner decisions / open findings register", "",
             "Generated: %s" % now, "",
             "Every finding **not** yet `verified-fixed`, with its status and reason. These require",
             "a human owner decision (product/infra/legal) or a follow-up; none are auto-closed.", ""]
    total = sum(len(r["items"]) for r in rows)
    lines += ["Total open/owner-gated: **%d**" % total, "",
              "| Repo | Finding | Sev | Title | Status | Note |", "|---|---|---|---|---|---|"]
    for r in sorted(rows, key=lambda x: x["repo"]):
        for it in r["items"]:
            note = (it["note"] or "").replace("|", "/")
            if len(note) > 100:
                note = note[:97] + "..."
            title = (it["title"] or "").replace("|", "/")
            if len(title) > 80:
                title = title[:77] + "..."
            lines.append("| %s | %s | %s | %s | %s | %s |" % (
                r["repo"], it["id"], it["severity"], title, it["status"], note))
    lines += ["", "## How to close", "",
              "1. Decide (product/infra/legal) and record the decision (linked issue/PR).",
              "2. Implement or explicitly accept/defer with an owner + date.",
              "3. Reconcile: `tools/remediation_status.py <run> --patch-set <PS> --state merged|closed`",
              "   (or `owner-accepted`), then `tools/normalize_register.py <run>`.",
              "", "---", "*Generated by repo-deep-dive tools/owner_decisions.py*"]
    md = "\n".join(lines) + "\n"
    if args.out:
        open(args.out, "w", encoding="utf-8").write(md)
        print("wrote %s (%d issue(s))" % (args.out, total))
    else:
        sys.stdout.write(md)
    if args.json_path:
        open(args.json_path, "w", encoding="utf-8").write(json.dumps(rows, indent=2) + "\n")
        print("wrote %s" % args.json_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
