#!/usr/bin/env python3
"""Generate the post-merge verification re-audit queue from the review index.

Reads a review-index.json (tools/review_index.py --json) and emits a Markdown queue:
per repo, its findings by severity, the PRs that were merged, and a post-merge
re-audit checklist. See runbooks/POST_MERGE_REAUDIT.md for the procedure.

Usage:
  tools/reaudit_queue.py --index-json review-index.json [--out REAUDIT_QUEUE.md]
"""

import argparse
import datetime
import json
import sys

sys.dont_write_bytecode = True

SEV = ("P0", "P1", "P2", "P3")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--index-json", required=True)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    rows = json.load(open(args.index_json, encoding="utf-8-sig"))
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    out = ["# Post-merge verification re-audit queue", "",
           "Generated: %s" % now, "",
           "Procedure: `runbooks/POST_MERGE_REAUDIT.md`. After the remediation PRs merged,",
           "run the machine checks and a verification-mode LLM re-audit per repo.", "",
           "| Repo | Findings | P0 | P1 | P2 | P3 | PRs merged | Re-audit |",
           "|---|---:|---:|---:|---:|---:|---:|---|"]
    total_prs = 0
    for r in sorted(rows, key=lambda x: x["repo"]):
        allf, prs = set(), set()
        for p in r["patchSets"]:
            allf.update(p["findings"])
            prs.update(p["prs"])
        sev = {s: 0 for s in SEV}
        for f in allf:
            s = f.split("-")[1]
            if s in sev:
                sev[s] += 1
        total_prs += len(prs)
        out.append("| %s | %d | %d | %d | %d | %d | %d | [ ] |" % (
            r["repo"], sum(sev.values()), sev["P0"], sev["P1"], sev["P2"], sev["P3"], len(prs)))
    out += ["", "Total: %d repos, %d PRs." % (len(rows), total_prs), "",
            "## Per-repo PR list", ""]
    for r in sorted(rows, key=lambda x: x["repo"]):
        prs = sorted({u for p in r["patchSets"] for u in p["prs"]})
        out.append("### %s" % r["repo"])
        for u in prs:
            out.append("- [x] %s" % u)
        if not prs:
            out.append("- _(no PRs — already-fixed-at-base or owner-blocked)_")
        out.append("")
    out += ["## Post-merge checklist", "",
            "1. Update the local clone to the default branch (`git fetch --prune origin`).",
            "2. Re-run the machine checks: `tools/deterministic_checks.py <repo> --deep`; compare to the",
            "   archived baseline and fail on new P0/P1.",
            "3. Run the verification-mode LLM re-audit (see the runbook) and diff new vs original findings.",
            "4. Reconcile merged sets to `verified-fixed` and refresh this queue.",
            "",
            "---", "*Generated by repo-deep-dive tools/reaudit_queue.py*"]
    md = "\n".join(out) + "\n"
    if args.out:
        open(args.out, "w", encoding="utf-8").write(md)
        print("wrote %s" % args.out)
    else:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
