#!/usr/bin/env python3
"""Render a dashboard for a repo-deep-dive run (read-only by default).

Reads findings via lib_findings and the advisory score via risk_score, then
emits a small static dashboard (Markdown + HTML) plus a PR-comment snippet.

Usage:
  python3 tools/render_dashboard.py <run-folder> [--write]

Read-only by default (prints a summary). --write emits dashboard.md,
dashboard.html, and pr_comment.md into the run folder. All output is
ASCII-safe (HTML-escaped, Windows-console safe).
"""

import argparse
import datetime
import html
import sys

sys.dont_write_bytecode = True

import lib_findings
import risk_score


def esc(text):
    return html.escape("" if text is None else str(text), quote=True)


def build_markdown(run_name, counts, by_area, score, advisory, findings):
    full = {"P0": 0, "P1": 0, "P2": 0, "P3": 0}
    full.update(counts)
    lines = [
        "# Audit Dashboard - %s" % run_name,
        "",
        "**Generated:** %s" % datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "**Score:** %d/100 (advisory; gate in RELEASE_GATE.md is authoritative)" % score,
        "**Advisory:** %s" % advisory,
        "",
        "## Severity",
        "",
        "| Severity | Count |",
        "|---|---|",
        "| P0 | %d |" % full["P0"],
        "| P1 | %d |" % full["P1"],
        "| P2 | %d |" % full["P2"],
        "| P3 | %d |" % full["P3"],
        "| Total | %d |" % sum(full.values()),
        "",
        "## Areas",
        "",
        "| Area | Count |",
        "|---|---|",
    ]
    for area, n in sorted(by_area.items()):
        lines.append("| %s | %d |" % (area, n))
    lines += ["", "## Top P0/P1", ""]
    top = [f for f in findings if f["severity"] in ("P0", "P1")][:20]
    if top:
        for f in top:
            lines.append("- **[%s]** %s: %s (%s:%d)" % (
                f["severity"], f["id"], f["title"], f["report"], f["line"]))
    else:
        lines.append("No P0/P1 findings.")
    lines += ["", "---", "*Generated by repo-deep-dive render_dashboard.py*"]
    return "\n".join(lines) + "\n"


def build_html(run_name, counts, by_area, score, advisory, findings):
    full = {"P0": 0, "P1": 0, "P2": 0, "P3": 0}
    full.update(counts)
    cls = "high" if score >= 85 else ("mid" if score >= 50 else "low")
    rows = "".join(
        "<tr><td>%s</td><td>%d</td></tr>\n" % (esc(a), n)
        for a, n in sorted(by_area.items())
    )
    top = "".join(
        "<tr><td>%s</td><td>%s</td><td>%s</td></tr>\n" % (
            esc(f["severity"]), esc(f["id"]), esc(f["title"]))
        for f in [x for x in findings if x["severity"] in ("P0", "P1")][:20]
    )
    return """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Audit Dashboard - %(run)s</title>
<style>
body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2em auto; }
.score { font-size: 4em; font-weight: bold; text-align: center; }
.score.high { color: #15803d; } .score.mid { color: #a16207; } .score.low { color: #b91c1c; }
table { width: 100%%; border-collapse: collapse; margin: 1em 0; }
th, td { border: 1px solid #999; padding: .5em; text-align: left; }
</style></head>
<body>
<h1>Audit Dashboard - %(run)s</h1>
<div class="score %(cls)s">%(score)d<small>/100</small></div>
<p style="text-align:center"><strong>Advisory:</strong> %(adv)s (gate in RELEASE_GATE.md is authoritative)</p>
<table>
<tr><th>Severity</th><th>Count</th></tr>
<tr><td>P0</td><td>%(p0)d</td></tr>
<tr><td>P1</td><td>%(p1)d</td></tr>
<tr><td>P2</td><td>%(p2)d</td></tr>
<tr><td>P3</td><td>%(p3)d</td></tr>
</table>
<h2>Areas</h2>
<table><tr><th>Area</th><th>Count</th></tr>
%(rows)s</table>
<h2>Top P0/P1</h2>
<table><tr><th>Sev</th><th>ID</th><th>Title</th></tr>
%(top)s</table>
</body></html>
""" % {"run": esc(run_name), "cls": cls, "score": score, "adv": esc(advisory),
       "p0": full["P0"], "p1": full["P1"], "p2": full["P2"], "p3": full["P3"],
       "rows": rows, "top": top}


def build_pr_comment(run_name, counts, score, advisory, findings):
    full = {"P0": 0, "P1": 0, "P2": 0, "P3": 0}
    full.update(counts)
    lines = [
        "## repo-deep-dive results - %s" % run_name,
        "",
        "Score: %d/100 (advisory) | Advisory: %s" % (score, advisory),
        "",
        "| Severity | Count |",
        "|---|---|",
        "| P0 | %d |" % full["P0"],
        "| P1 | %d |" % full["P1"],
        "| P2 | %d |" % full["P2"],
        "| P3 | %d |" % full["P3"],
        "",
        "Full gate: RELEASE_GATE.md in the run folder.",
    ]
    top = [f for f in findings if f["severity"] in ("P0", "P1")][:15]
    if top:
        lines += ["", "### Top findings", ""]
        for f in top:
            lines.append("- **[%s]** %s: %s" % (f["severity"], f["id"], f["title"]))
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("run_dir")
    ap.add_argument("--write", action="store_true",
                    help="write dashboard.md, dashboard.html, pr_comment.md into the run folder")
    args = ap.parse_args()

    run, findings, dupes = lib_findings.collect_with_dupes(args.run_dir)
    for fid, reps in sorted(dupes.items()):
        print("warning: duplicate finding ID %s in: %s" % (fid, ", ".join(reps)),
              file=sys.stderr)

    c = lib_findings.counts(findings)
    full = {"P0": 0, "P1": 0, "P2": 0, "P3": 0}
    full.update(c["bySeverity"])
    score = risk_score.score_counts(full)
    adv = risk_score.advisory(full, score)

    print("run: %s" % run.name)
    print("findings: %d score: %d/100 advisory: %s" % (c["total"], score, adv))

    if args.write:
        (run / "dashboard.md").write_text(
            build_markdown(run.name, full, c["byArea"], score, adv, findings),
            encoding="utf-8")
        (run / "dashboard.html").write_text(
            build_html(run.name, full, c["byArea"], score, adv, findings),
            encoding="utf-8")
        (run / "pr_comment.md").write_text(
            build_pr_comment(run.name, full, score, adv, findings),
            encoding="utf-8")
        print("wrote dashboard.md, dashboard.html, pr_comment.md")


if __name__ == "__main__":
    main()
